name: Download a Build Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
        type: string
      destination:
        description: 'Destination path'
        required: false
        default: 'artifacts'
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@a9bc5e6ef2cb54c177f32aa5726adaa15e7e2d59  # v3.1.0
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.destination }}
