name: Rubric Scores

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rubric-evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4

      - name: Install
        run: npm ci

      - name: Generate rubric scores
        run: npm run rubric:evaluate

      - name: Upload rubric artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: scores-csv
          path: |
            ./scores.csv
            ./scores.json
            ./report.html
          if-no-files-found: error
          retention-days: 30
